#+TITLE: reformr 開発プロジェクトノート
#+PROPERTY: header-args :cache yes :exports code :results scalar
#+STARTUP: contents
* 開発準備
#+BEGIN_SRC R
getwd()
# devtools::create("otolithr")
#+END_SRC

* 古いコード
** マイワシ
library(beepr)
MINIMUM_SAMPLE  <- 5
MEASURED_DATA <- read.csv("ksdSardine_measuredData_YK.csv")
TRAWL_INFO    <-  read.csv("/Volumes/USER_DRV/fromHyokaken/YK2001-2016Stations.csv")
COL_ADJUST      <- 0.8
INDIR           <- "/Volumes/USER_DRV/ratoc_b/"
BL_AT_HATCH   <- c(5.9, 5.6)
# for sardine Takahashi et al. 2008 Year-class strength...
# for anchovy: Fukuhara 1983 Development and growth of laboratory reared... rewied by cf. Zenitani and Kono 2012 Daily growth rate model...
SCIENTIFIC_FISHNAMES <- c("Sardinops-melanostictus","Engraulis-japonicus")
INCNUM2AGE      <- c(2,3)
PREFECTURES     <- c("Tottori", "Toyama")
HDRFILES        <- list.files(INDIR, pattern=".+hdr")
print(HDRFILES)
out <- NULL
for(i in 1:length(HDRFILES)){
  hdrname                   <- HDRFILES[i]
  split                     <- unlist(strsplit(hdrname, "_"))
  spcs_name                 <- split[2]
  place_or_cruise           <- split[3]
  year                      <- substr(split[4],1,4)
  month                     <- substr(split[4],5,6); if(month!="MM"){month <- as.numeric(month)}
  day                       <- substr(split[4],7,8); if(day!="DD"){day <- as.numeric(day)}
  date                      <- paste(year, formatC(month, width=2, flag=0), formatC(day, width=2, flag=0), sep="-")
  station                   <- split[5]
  sample_no                 <- as.numeric(gsub(".hdr","",split[6]))
  infile                    <- paste(INDIR, hdrname, sep="/")
  data_org                  <- read.csv(infile, fileEncoding = "CP932", header = F)
  first_increment_position  <- which(as.character(data_org[,1])=="日輪幅")+1
  inc_data                  <- as.numeric(as.character(data_org[first_increment_position:nrow(data_org),1]))
  otolith_radius            <- inc_data[1]
  for(j in 2:length(inc_data)){
    otolith_radius <- append(otolith_radius, otolith_radius[j-1]+inc_data[j])
  }
  inc_num                   <- 1:length(inc_data)
  age                       <- length(inc_data) + INCNUM2AGE[which(spcs_name==SCIENTIFIC_FISHNAMES)]
  n_day_before_catch        <- age - inc_num - INCNUM2AGE[which(spcs_name==SCIENTIFIC_FISHNAMES)]
  out                       <- rbind(out, cbind(spcs_name, place_or_cruise, year, month, day, date, station, sample_no, inc_num, age, n_day_before_catch,inc_data, otolith_radius))
  if(sum(is.na(out[i,]))>0){browser()}
}
out           <- as.data.frame(out)
colnames(out) <- c("scientificName", "placeOrCruise", "yearCollected", "monthCollected", "dayCollected", "dateCollected", "station", "sampleNo", "incNum", "age", "nDayBeforeCatch","incWidth_microm", "otolithRadius_microm")
for(j in 1:ncol(out)){
  if(sum(is.na(out[,j]))>0){
    browser()
  }
}
write.csv(out, "otolith_merged.csv", row.names = F)
DATA_ORG <- read.csv("otolith_merged.csv")


DATA <- subset(DATA_ORG, placeOrCruise=="Tottori" |  placeOrCruise=="Toyama")
# DATA <- DATA_ORG


PLACELIST <- unique(DATA$placeOrCruise)
plot(1,1, xlim=c(0, max(DATA$incNum)), ylim=c(0, max(DATA$incWidth_microm)), type="n")
par(new=T)
gitter <- 0
for(p in PLACELIST){
  pdata     <- subset(DATA, placeOrCruise==p)
  datelist  <- unique(pdata$dateCollected)
  for(date in datelist){
    datedata    <- subset(pdata, dateCollected==date)
    max_incnum  <- max(datedata$incNum)
    mean_iw     <- NULL
    sd          <- NULL
    mean_incno  <- NULL
    for(i in 1:max_incnum){
      idata <- subset(datedata, incNum==i)
      if(nrow(idata)<MINIMUM_SAMPLE){
        break
      }
      mean_iw     <- append(mean_iw, mean(idata$incWidth_microm))
      mean_incno  <- append(mean_incno, i)
      sd          <- append(sd, sd(idata$incWidth_microm))
    }
    if(is.null(mean_incno)==F){
      mean_color <- rgb(which(PLACELIST==p)/length(PLACELIST)*COL_ADJUST, which(datelist==date)/length(datelist)*COL_ADJUST, 0.5*COL_ADJUST)
      samplelist  <- unique(datedata$sampleNo)
      for(sample in samplelist){
        individual <- subset(datedata, sampleNo==sample)
        color <- rgb(which(PLACELIST==p)/length(PLACELIST), which(datelist==date)/length(datelist), which(samplelist==sample)/length(samplelist))
        lines(individual$incNum, individual$incWidth_microm, col=color)
      }
      lines(mean_incno+gitter, mean_iw, col=mean_color, lwd=4)
      arrows(mean_incno+gitter, mean_iw-sd, mean_incno+gitter, mean_iw+sd, length=0, col=mean_color, lwd=2.5)
      text(mean_incno[length(mean_incno)], mean_iw[length(mean_incno)], paste(date, p), col=mean_color, pos=1, cex=2)
      gitter <- gitter+0.2
    } 
  }
}
DATA$ID       <- paste(DATA$scientificName, DATA$placeOrCruise, gsub("-","", DATA$dateCollected), DATA$station, formatC(DATA$sampleNo,width=3, flag=0), sep="_")
DATA$ID       <- gsub("NA", "", DATA$ID)

for(i in SCIENTIFIC_FISHNAMES){
  DATA[DATA[,"scientificName"]==i,"BLAtHatch_mm"] <- BL_AT_HATCH[which(SCIENTIFIC_FISHNAMES==i)]
}
out2 <- NULL
for(i in 1:nrow(DATA)){
  iout       <- DATA[i, ]
  otolithid  <- gsub("MT0","MT",iout$ID)
  otl_split  <- unlist(strsplit(otolithid, "_"))
  cruise_stn <- paste(otl_split[2], otl_split[4], sep="_")
  itrawlinfo <- subset(TRAWL_INFO, ID1==cruise_stn)
  if(nrow(itrawlinfo)>0){
    date       <- as.Date(as.character(itrawlinfo$Date))
    iout$dateCollected  <- date
    iout$yearCollected  <- substr(date,1,4)
    iout$monthCollected <- substr(date,6,7)
    iout$dayCollected   <- substr(date, 9,10)
  }
  out2                <- rbind(out2, iout)
}
MEASURED_DATA <- read.csv("/Volumes/USER_DRV/fromHyokaken/Tottori_Toyama.csv")
out <- NULL
for(p in PREFECTURES){
  otolith_data  <- subset(out2, placeOrCruise==p)
  for(i in 1:nrow(otolith_data)){
    otolith_id            <- otolith_data[i, "ID"]
    i_measured_data       <- subset(MEASURED_DATA, ID==otolith_id)
    if(nrow(i_measured_data)>0){
      scaledBodyLength_mm <- i_measured_data$scaledBodyLength_mm
      wetWeight_g         <- i_measured_data$wetWeight_g
      out                 <- rbind(out, cbind(otolith_data[i, ], scaledBodyLength_mm, wetWeight_g))
    }
  }
}
out <- as.data.frame(out)
IDLIST  <- unique(out$ID)
out$ORAtHatch_microm <- NA
out$ORAtCatch_microm <- NA
for(i in IDLIST){
  idata <- subset(out, ID==i)
  out[out[,"ID"]==i,"ORAtHatch_microm"] <- out[out[,"ID"]==i & out[,"incNum"]==1, "otolithRadius_microm"]
  out[out[,"ID"]==i,"ORAtCatch_microm"] <- out[out[,"ID"]==i & out[,"nDayBeforeCatch"]==0, "otolithRadius_microm"]
}
out$a_forBackCal <- (out$BLAtHatch_mm - out$scaledBodyLength_mm) / (out$ORAtHatch_microm - out$ORAtCatch_microm)
out$b_forBackCal <- out$scaledBodyLength_mm - out$a_forBackCal * out$ORAtCatch_microm
out$backCalBL_mm <- out$a_forBackCal * out$otolithRadius_microm + out$b_forBackCal
out$deltaBL_mm    <- NA
out2 <- NULL
for(i in IDLIST){
  iout <- subset(out, ID==i)
  iout[1, "deltaBL_mm"] <- 0
  for(i in 2:nrow(iout)){
    iout[i, "deltaBL_mm"] <- iout[i, "backCalBL_mm"] - iout[i-1, "backCalBL_mm"]
  }
  out2 <- rbind(out2, iout)
}
out2$hatchDate <- as.Date(as.character(out2$dateCollected)) - as.numeric(out2$age)
plot(out2$age, out2$scaledBodyLength_mm, xlim=c(0,230), ylim=c(0,150), type="n")
out2$placeDate <- paste(out2$placeOrCruise, out2$dateCollected, sep="")
PLACEDATELIST <- unique(out2$placeDate)
for(i in 1:nrow(out2)){
  idata <- out2[i,]
  if(idata$incNum==1){
    color <- which(PLACEDATELIST==idata$placeDate)
    points(idata$age, idata$scaledBodyLength_mm, col=color, pch=16)
    text(idata$age, idata$scaledBodyLength_mm, idata$sampleNo, pos=4, col=color)
    if(idata$sampleNo==1){
      text(idata$age, idata$scaledBodyLength_mm, idata$placeDate, col=color)
    }
  }
}
write.csv(out2, "otolith_merged.csv", row.names=F)
beep(8)

** マアジ
library(stringr)
library(beepr)
# otolith data
PARENTDIR             <- "/Volumes/USER_DRV"
DATDIRS               <- c("simane/data", "otolith_takahashi/Shimane201406/data", 'otolith_takahashi/MZH1406/data', 'otolith_takahashi/Tottori201405/data', 'otolith_takahashi/YK1406/data')
OUTDIR                <- "/Volumes/USER_DRV/R_to_Ratoc"
MEASURED_DATA         <- read.csv("ksdJmckerel_MeasuredData_writtenByR.csv")
MINIMUM_SAMPLE        <- 5
SCIENTIFIC_NAME       <- "Trachurus-japonicus"
INCNUM2AGE            <- 2 # Xie et al. 2005 J Fish Biol 66, 1704-1719
SL_AT_HATCH_mm        <- 2.65 # Xie et al. 2005 JFB 66 
out                   <- NULL
for(d in DATDIRS){
  data_dir <- paste(PARENTDIR, d, sep="/")
  hdrfiles <- list.files(data_dir, pattern=".+hdr")
  dsplit   <- unlist(strsplit(d, '/'))
  for(i in 1:length(hdrfiles)){
    hdrname                   <- hdrfiles[i]
    split                     <- unlist(strsplit(hdrname, "-"))
    if(d=="simane/data"){
      cruisename  <- paste(gsub("si", "Shi", substr(split[1], 1, 10)), 'JM', sep='')
      station     <- str_to_upper(substr(split[1], 11, nchar(split)))
    }
    if(gregexpr('Shimane201406', d)>0){ # by Takahashi
      cruisename  <- paste(gsub("20", "", dsplit[2]), 'JM', sep='')
      station     <- str_to_upper(gsub("t", "", split[1]))
    }
    if(gregexpr('Tottori201405', d)>0){
      cruisename      <- paste(gsub("20", "", gsub('05', '',dsplit[2])), 'JM', sep='')
      pre_station     <- str_to_upper(split[1])
      prefix_station  <- gsub('[0-9]', '', pre_station)
      numeric_station <- formatC(as.numeric(gsub('[A-Z]', '', pre_station)), width=2, flag=0)
      station         <- paste(prefix_station, numeric_station, sep='')
    }
    if(gregexpr('MZH1406', d)>0){
      cruisename  <- dsplit[2]
      station     <- split[1]
    }
    if(gregexpr('YK1406', d)>0){
      cruisename  <- 'YK1403' # Cruise No. 3 conducted from May to Jun
      station     <- split[1]
    }
    sample_no                 <- as.numeric(gsub(".hdr", "", split[2]))
    corresponding_measure_data<- subset(MEASURED_DATA, CruiseName==cruisename & Station==station & SampleNo==sample_no)
    n_collected               <- gsub(",", "", corresponding_measure_data$N_Trachurus_japonicus)
    date                      <- as.character(corresponding_measure_data$DateCollected)
    year                      <- substr(date,1,4)
    month                     <- substr(date,6,7)
    day                       <- substr(date,9,10)
    spcs_name                 <- SCIENTIFIC_NAME
    infile                    <- paste(data_dir, hdrname, sep="/")
    data_org                  <- read.csv(infile, fileEncoding = "CP932", header = F, stringsAsFactors=F)
    data_org[, 2]             <- as.character(data_org[, 2])
    first_increment_position  <- which(as.character(data_org[,1])=="日輪幅")+1
    inc_data                  <- as.numeric(as.character(data_org[first_increment_position:(nrow(data_org)-0),1]))
    inc_num                   <- 1:length(inc_data)
    otolith_radius_microm     <- inc_data[1]
    for(ii in 2:length(inc_data)){
      otolith_radius_microm <- append(otolith_radius_microm, otolith_radius_microm[ii-1]+inc_data[ii])
    }
    or_at_catch_microm        <- sum(inc_data)
    n_day_before_catch        <- (rev(inc_num)-1)
    age_at_catch              <- length(inc_data) + INCNUM2AGE
    age_backcalculated        <- inc_num + INCNUM2AGE
    standard_length_mm        <- corresponding_measure_data$StandardLength_mm
    wetweight_mg              <- corresponding_measure_data$WetWeight_mg
    age_at_2nd_primordia      <- corresponding_measure_data$AgeAtSecondaryPrimordia
    if(is.na(age_at_2nd_primordia)==T){
      age_at_2nd_primordia <- 0
    }
    intercept_for_backcal     <- (SL_AT_HATCH_mm*or_at_catch_microm - standard_length_mm*otolith_radius_microm[1])/(or_at_catch_microm - otolith_radius_microm[1])
    slope_for_backcal         <- (standard_length_mm - intercept_for_backcal)/or_at_catch_microm
    back_calculated_sl_mm     <- otolith_radius_microm * slope_for_backcal + intercept_for_backcal
    out                       <- rbind(out, cbind(spcs_name, cruisename, date, year, month, day, station, n_collected, sample_no, standard_length_mm, wetweight_mg, age_at_2nd_primordia, inc_num, age_backcalculated, n_day_before_catch, age_at_catch,inc_data, otolith_radius_microm, back_calculated_sl_mm))
    if(sum(is.na(out[i,]))>0){browser()}
    new_filename              <- paste(cruisename, "_", station, "_",  gsub("-", "", date), "_", spcs_name, "_", sample_no, ".hdr", sep="") 
    file.copy(paste(data_dir, gsub("hdr", "IFG", hdrname), sep="/"), paste(OUTDIR, gsub("hdr", "IFG", new_filename), sep="/"))
    file.copy(paste(data_dir, gsub("hdr", "ISC", hdrname), sep="/"), paste(OUTDIR, gsub("hdr", "ISC", new_filename), sep="/"))
    file.copy(paste(data_dir, gsub("hdr", "POL", hdrname), sep="/"), paste(OUTDIR, gsub("hdr", "POL", new_filename), sep="/"))
    data_org[data_org[, 1]=="標本番号", 2]              <- new_filename
    data_org[data_org[, 1]=="採集航海番号", 2]          <- cruisename
    data_org[data_org[, 1]=="採集ｽﾃｰｼｮﾝ番号", 2]        <- station
    data_org[data_org[, 1]=="採集日付", 2]              <- date
    data_org[data_org[, 1]=="体長", 2]                  <- standard_length_mm
    data_org[data_org[, 1]=="体重", 2]                  <- wetweight_mg
    write.table(data_org, paste(OUTDIR, new_filename, sep="/"), row.names=F, col.names=F, sep=",", quote=F, fileEncoding="cp932")
  }
}
out           <- as.data.frame(out)
colnames(out) <- c("scientificName", "placeOrCruise", "dateCollected", "yearCollected", "monthCollected", "dayCollected", "station", "nCollected", "sampleNo", "standardLength_mm", "wetWeight_mg", 'ageAt2ndPrimordia',  "incNum", "ageBackCalculated", "nDayBeforeCatch", "ageAtCatch","incWidth_microm", "otolithRadius_microm", "backCalculatedSL_mm")
for(j in 1:ncol(out)){
  if(sum(is.na(out[,j]))>0){
    browser()
  }
}
ID1 <- paste(out$placeOrCruise, out$station, gsub("-", "", out$dateCollected), sep="_")
ID2 <- paste(ID1, out$scientificName, out$sampleNo, sep="_")
out <- cbind(ID1, ID2, out)
out$dateCollected <- as.Date(as.character(out$dateCollected))
out$ageAtCatch    <- as.numeric(as.character(out$ageAtCatch))
out$hatchDate <- out$dateCollected - out$ageAtCatch
write.csv(out, "./ksdJmckerel_otolithData_writtenbyR.csv", row.names = F)
DATA <- read.csv("ksdJmckerel_otolithData_writtenbyR.csv")
beep(2)


